sudo: required
language: node_js
node_js:
    - 10.8.0
install:
  - npm i
script:
  - npm install codecov -g
  - npm run lint
  # - npx ng build @chakray/hero
  - npx ng test --watch=false --code-coverage
  - BUILD=`date +%s`; sed -ie "s/BUILD/$BUILD/g" ./src/environments/environment.prod.ts
  - npx ng build --prod --deploy-url /hero/ --base-href /hero/
  - cp src/404.html dist/hero
cache:
    directories:
      - node_modules
after_success:
  - codecov
before_deploy:
  - if [[ $TRAVIS_TAG ]]; then
      if [[ $PWD != *"dist/chakray/hero" ]]; then cd dist/chakray/hero; fi;
    fi;
deploy:
  - provider: pages
    local-dir: dist/hero
    github-token: $github
    skip-cleanup: true
    keep-history: true
  - provider: npm
    email: $npm_email
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $github
    skip_cleanup: true
    draft: true
    on:
      tags: true
